
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;
	private global::Gtk.Label entrada1;
	private global::Gtk.Entry numero1;
	private global::Gtk.Entry numero2;
	private global::Gtk.Button btnmult;
	private global::Gtk.Button btnDiv;
	private global::Gtk.Label entrada2;
	private global::Gtk.Button btnSumar;
	private global::Gtk.Label salida;
	private global::Gtk.Entry resultado;
	private global::Gtk.Button btnRestar;
	
	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed ();
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entrada1 = new global::Gtk.Label ();
		this.entrada1.Name = "entrada1";
		this.entrada1.Xalign = 1F;
		this.entrada1.LabelProp = global::Mono.Unix.Catalog.GetString ("Ingresa numero 1");
		this.fixed1.Add (this.entrada1);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entrada1]));
		w1.X = 52;
		w1.Y = 39;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero1 = new global::Gtk.Entry ();
		this.numero1.CanFocus = true;
		this.numero1.Name = "numero1";
		this.numero1.IsEditable = true;
		this.numero1.InvisibleChar = '●';
		this.fixed1.Add (this.numero1);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero1]));
		w2.X = 178;
		w2.Y = 36;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.numero2 = new global::Gtk.Entry ();
		this.numero2.CanFocus = true;
		this.numero2.Name = "numero2";
		this.numero2.IsEditable = true;
		this.numero2.InvisibleChar = '●';
		this.fixed1.Add (this.numero2);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.numero2]));
		w3.X = 176;
		w3.Y = 69;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnmult = new global::Gtk.Button ();
		this.btnmult.CanFocus = true;
		this.btnmult.Name = "btnmult";
		this.btnmult.UseUnderline = true;
		this.btnmult.Label = global::Mono.Unix.Catalog.GetString ("Multiplicar");
		this.fixed1.Add (this.btnmult);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnmult]));
		w4.X = 187;
		w4.Y = 197;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnDiv = new global::Gtk.Button ();
		this.btnDiv.CanFocus = true;
		this.btnDiv.Name = "btnDiv";
		this.btnDiv.UseUnderline = true;
		this.btnDiv.Label = global::Mono.Unix.Catalog.GetString ("Dividir");
		this.fixed1.Add (this.btnDiv);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnDiv]));
		w5.X = 292;
		w5.Y = 198;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.entrada2 = new global::Gtk.Label ();
		this.entrada2.Name = "entrada2";
		this.entrada2.LabelProp = global::Mono.Unix.Catalog.GetString ("Ingresa el segundo numeo");
		this.fixed1.Add (this.entrada2);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.entrada2]));
		w6.X = 15;
		w6.Y = 73;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnSumar = new global::Gtk.Button ();
		this.btnSumar.CanFocus = true;
		this.btnSumar.Name = "btnSumar";
		this.btnSumar.UseUnderline = true;
		this.btnSumar.Label = global::Mono.Unix.Catalog.GetString ("Sumar\n");
		this.fixed1.Add (this.btnSumar);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnSumar]));
		w7.X = 17;
		w7.Y = 190;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.salida = new global::Gtk.Label ();
		this.salida.Name = "salida";
		this.salida.LabelProp = global::Mono.Unix.Catalog.GetString ("Resultado");
		this.fixed1.Add (this.salida);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.salida]));
		w8.X = 47;
		w8.Y = 110;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.resultado = new global::Gtk.Entry ();
		this.resultado.CanFocus = true;
		this.resultado.Name = "resultado";
		this.resultado.IsEditable = true;
		this.resultado.InvisibleChar = '●';
		this.fixed1.Add (this.resultado);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.resultado]));
		w9.X = 174;
		w9.Y = 105;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnRestar = new global::Gtk.Button ();
		this.btnRestar.CanFocus = true;
		this.btnRestar.Name = "btnRestar";
		this.btnRestar.UseUnderline = true;
		this.btnRestar.Label = global::Mono.Unix.Catalog.GetString ("Restar\n");
		this.fixed1.Add (this.btnRestar);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1 [this.btnRestar]));
		w10.X = 104;
		w10.Y = 188;
		this.Add (this.fixed1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.btnmult.Clicked += new global::System.EventHandler (this.OnBtnmultClicked);
		this.btnDiv.Clicked += new global::System.EventHandler (this.OnBtnDivClicked);
		this.btnSumar.Clicked += new global::System.EventHandler (this.OnBtnSumarClicked);
		this.btnRestar.Clicked += new global::System.EventHandler (this.OnBtnRestarClicked);
	}
}
